### ISSUE TITLE
fatal error for source code

### ISSUE THREAD

**Issue by VentsislavDinev** [NikolayIT/OpenJudgeSystem#536]
I downloaded the repositorys but have problems with mising method  and charackers. I build all solution  then throw problems in error list.
If you've got any question i am here for answer

**Comment by NikolayIT** [comment]
Could you please paste the output of the compiler (the list of compilation errors)?

**Comment by VentsislavDinev** [comment]
Error	59	Unexpected character '$'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\Helpers\JavaCodePreprocessorHelper.cs	26	38	OJS.Workers.Common
Error	81	The name 'nameof' does not exist in the current context	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\PlagiarismDetectorTypeExtensions.cs	27	25	OJS.Common
Error	82	The name 'nameof' does not exist in the current context	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\ExpressionBuilder.cs	16	49	OJS.Common
Error	83	The name 'nameof' does not exist in the current context	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\ExpressionBuilder.cs	21	49	OJS.Common
Error	85	The name 'nameof' does not exist in the current context	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\EnumExtensions.cs	38	86	OJS.Common
Error	89	The name 'Length' does not exist in the current context	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	53	OJS.Common
Error	80	The name 'GetProperty' does not exist in the current context	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Attributes\LocalizedDescriptionAttribute.cs	11	50	OJS.Common
Error	2	Syntax error, ':' expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Attributes\LocalizedDescriptionAttribute.cs	11	50	OJS.Common
Error	4	Syntax error, ':' expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	53	OJS.Common
Error	58	Syntax error, ':' expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Attributes\LocalizedDisplayFormatAttribute.cs	11	70	OJS.Common
Error	84	Property or indexer 'OJS.Data.Contracts.DataAnnotations.IsUnicodeAttribute.IsUnicode' cannot be assigned to -- it is read only	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\DataAnnotations\IsUnicodeAttribute.cs	9	13	OJS.Data.Contracts
Error	88	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	53	OJS.Common
Error	90	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	63	OJS.Common
Error	91	Only assignment, call, increment, decrement, await, and new object expressions can be used as a statement	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	68	OJS.Common
Error	51	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Tools\bin\Debug\OJS.Workers.Tools.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Tools.Tests\CSC	OJS.Workers.Tools.Tests
Error	79	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Tools\bin\Debug\OJS.Workers.Tools.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web\CSC	OJS.Web
Error	20	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\bin\Debug\OJS.Workers.Executors.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\CSC	OJS.Workers.ExecutionStrategies
Error	27	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\bin\Debug\OJS.Workers.Executors.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Agent\CSC	OJS.Workers.Agent
Error	32	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\bin\Debug\OJS.Workers.Executors.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SandboxExecutorProofOfConcept\CSC	SandboxExecutorProofOfConcept
Error	35	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\bin\Debug\OJS.Workers.Executors.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Executors.Tests\CSC	OJS.Workers.Executors.Tests
Error	44	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\bin\Debug\OJS.Workers.Executors.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	43	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\bin\Debug\OJS.Workers.ExecutionStrategies.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	52	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\bin\Debug\OJS.Workers.ExecutionStrategies.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.ExecutionStrategies.Tests\CSC	OJS.Workers.ExecutionStrategies.Tests
Error	54	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\bin\Debug\OJS.Workers.ExecutionStrategies.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SqlTestingPoC\CSC	SqlTestingPoC
Error	19	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\bin\Debug\OJS.Workers.Compilers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\CSC	OJS.Workers.ExecutionStrategies
Error	26	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\bin\Debug\OJS.Workers.Compilers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Agent\CSC	OJS.Workers.Agent
Error	42	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\bin\Debug\OJS.Workers.Compilers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	47	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\bin\Debug\OJS.Workers.Compilers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Compilers.Tests\CSC	OJS.Workers.Compilers.Tests
Error	69	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\bin\Debug\OJS.Workers.Compilers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Tools\CSC	OJS.Workers.Tools
Error	13	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Checkers\CSC	OJS.Workers.Checkers
Error	15	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\CSC	OJS.Workers.Executors
Error	18	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\CSC	OJS.Workers.ExecutionStrategies
Error	22	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Controller\CSC	OJS.Workers.Controller
Error	25	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Agent\CSC	OJS.Workers.Agent
Error	29	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Checkers.Tests\CSC	OJS.Workers.Checkers.Tests
Error	31	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SandboxExecutorProofOfConcept\CSC	SandboxExecutorProofOfConcept
Error	34	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Executors.Tests\CSC	OJS.Workers.Executors.Tests
Error	41	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	46	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Compilers.Tests\CSC	OJS.Workers.Compilers.Tests
Error	53	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SqlTestingPoC\CSC	SqlTestingPoC
Error	63	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\CSC	OJS.Workers.Compilers
Error	68	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\bin\Debug\OJS.Workers.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Tools\CSC	OJS.Workers.Tools
Error	17	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Checkers\bin\Debug\OJS.Workers.Checkers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\CSC	OJS.Workers.ExecutionStrategies
Error	24	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Checkers\bin\Debug\OJS.Workers.Checkers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Agent\CSC	OJS.Workers.Agent
Error	28	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Checkers\bin\Debug\OJS.Workers.Checkers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Checkers.Tests\CSC	OJS.Workers.Checkers.Tests
Error	40	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Checkers\bin\Debug\OJS.Workers.Checkers.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	78	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web.Common\bin\Debug\OJS.Web.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web\CSC	OJS.Web
Error	33	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SandboxTarget\bin\Debug\SandboxTarget.exe' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SandboxExecutorProofOfConcept\CSC	SandboxExecutorProofOfConcept
Error	12	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Checkers\CSC	OJS.Workers.Checkers
Error	14	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Executors\CSC	OJS.Workers.Executors
Error	16	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.ExecutionStrategies\CSC	OJS.Workers.ExecutionStrategies
Error	21	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Common.Tests\CSC	OJS.Common.Tests
Error	23	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Agent\CSC	OJS.Workers.Agent
Error	30	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tools\SandboxExecutorProofOfConcept\CSC	SandboxExecutorProofOfConcept
Error	36	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	45	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Workers.Compilers.Tests\CSC	OJS.Workers.Compilers.Tests
Error	60	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\CSC	OJS.Data.Models
Error	62	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Compilers\CSC	OJS.Workers.Compilers
Error	64	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\CSC	OJS.Data
Error	67	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Tools\CSC	OJS.Workers.Tools
Error	70	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web.Common\CSC	OJS.Web.Common
Error	74	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\bin\Debug\OJS.Common.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web\CSC	OJS.Web
Error	38	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\bin\Debug\OJS.Data.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	49	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\bin\Debug\OJS.Data.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Tests.Common\CSC	OJS.Tests.Common
Error	72	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\bin\Debug\OJS.Data.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web.Common\CSC	OJS.Web.Common
Error	76	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\bin\Debug\OJS.Data.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web\CSC	OJS.Web
Error	39	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\bin\Debug\OJS.Data.Models.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	50	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\bin\Debug\OJS.Data.Models.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Tests.Common\CSC	OJS.Tests.Common
Error	66	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\bin\Debug\OJS.Data.Models.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\CSC	OJS.Data
Error	73	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\bin\Debug\OJS.Data.Models.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web.Common\CSC	OJS.Web.Common
Error	77	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\bin\Debug\OJS.Data.Models.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web\CSC	OJS.Web
Error	37	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\bin\Debug\OJS.Data.Contracts.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.LocalWorker\CSC	OJS.Workers.LocalWorker
Error	48	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\bin\Debug\OJS.Data.Contracts.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Tests\OJS.Tests.Common\CSC	OJS.Tests.Common
Error	61	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\bin\Debug\OJS.Data.Contracts.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Models\CSC	OJS.Data.Models
Error	65	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\bin\Debug\OJS.Data.Contracts.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\CSC	OJS.Data
Error	71	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\bin\Debug\OJS.Data.Contracts.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web.Common\CSC	OJS.Web.Common
Error	75	Metadata file 'C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\bin\Debug\OJS.Data.Contracts.dll' could not be found	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Web\OJS.Web\CSC	OJS.Web
Error	10	Invalid token '+' in class, struct, or interface member declaration	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\ProcessExecutionResult.cs	33	76	OJS.Workers.Common
Error	11	Invalid token ';' in class, struct, or interface member declaration	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\ProcessExecutionResult.cs	33	100	OJS.Workers.Common
Error	1	Invalid expression term '.'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Attributes\LocalizedDescriptionAttribute.cs	11	49	OJS.Common
Error	3	Invalid expression term '.'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	52	OJS.Common
Error	57	Invalid expression term '.'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Attributes\LocalizedDisplayFormatAttribute.cs	11	69	OJS.Common
Error	5	Invalid expression term ')'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	64	OJS.Common
Error	7	Invalid expression term ')'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	73	OJS.Common
Error	6	; expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	64	OJS.Common
Error	8	; expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\OJS.Common\Extensions\StringExtensions.cs	64	73	OJS.Common
Error	9	; expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\ProcessExecutionResult.cs	33	44	OJS.Workers.Common
Error	55	; expected	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data\OjsDbContext.cs	65	36	OJS.Data
Error	87	'OJS.Workers.Common.ProcessExecutionResult.UserProcessorTime' is a 'property' but is used like a 'type'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\ProcessExecutionResult.cs	33	83	OJS.Workers.Common
Error	86	'OJS.Workers.Common.ProcessExecutionResult.PrivilegedProcessorTime' is a 'property' but is used like a 'type'	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Workers\OJS.Workers.Common\ProcessExecutionResult.cs	33	52	OJS.Workers.Common
Error	56	'OJS.Data.Contracts.DataAnnotations.IsUnicodeAttribute.IsUnicode.get' must declare a body because it is not marked abstract or extern. Automatically implemented properties must define both get and set accessors.	C:\Users\Toshiba\Desktop\OpenJudgeSystem-master\Open Judge System\Data\OJS.Data.Contracts\DataAnnotations\IsUnicodeAttribute.cs	12	33	OJS.Data.Contracts
this is all errors.

**Comment by Teodor92** [comment]
Are you using C# 6.0?

**Comment by NikolayIT** [comment]
Try installing and compiling with Visual Studio 2015.

**Comment by VentsislavDinev** [comment]
Yes. Now i note have problems. Thanks :)
